backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img
editor:
  preview: true
collections:
  - name: "post" 
    label: "Post" 
    folder: "site/content/post"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    create: true
    files:
      - file: "content/_index.md"
        label: "Home"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: text}
          - {label: "Quotes", name: quotes, widget: list, fields: [
              {label: "Quote", name: "quote", widget: "text"},
              {label: "Author", name: "author", widget: "string"}]}
      - file: "content/girls.md"
        label: "Girls"
        name: "girls"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: text}
          - {label: "Quotes", name: quotes, widget: list, fields: [
              {label: "Quote", name: "quote", widget: "text"},
              {label: "Author", name: "author", widget: "string"}]}