backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Home"
        name: "home"
        fields:
          - {label: Title, name: title, widget: text}
          - {label: Subtitle, name: subtitle, widget: text}
      - file: "content/_contact.md"
        label: "Contact"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: text}
          - {label: Subtitle, name: subtitle, widget: text}
  - name: "partials"
    label: "Partials"
    files:
      - file: "content/partials/timeline/_index.md"
        label: "Timeline"
        name: "timeline"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: date, name: date, widget: string}