backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img
show_preview_links: true
collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Home"
        name: "home"
        fields:
          - label: "Header"
            name: "header"
            widget: "object"
            fields:
              - { label: Header Title, name: title, widget: text }
              - { label: Header Subtitle, name: subtitle, widget: text }
          - label: "Column Left"
            name: "columnLeft"
            widget: "object"
            fields:
              - { label: Title, name: title, widget: text }
              - {
                  label: Copy Set One,
                  name: copySetOne,
                  widget: list,
                  fields: [{ label: Text, name: text, widget: markdown }],
                }
              - {
                  label: Quote,
                  name: quote,
                  widget: object,
                  fields:
                    [
                      { label: Text, name: text, widget: text },
                      { label: author, name: author, widget: string }
                    ],
                }
              - {
                  label: Copy Set Two,
                  name: copySetTwo,
                  widget: list,
                  fields: [{ label: Text, name: text, widget: text }],
                }
          - label: "Column Right"
            name: "columnRight"
            widget: "object"
            fields:
              - { label: Criteria, name: criteria, widget: markdown }
              - {
                  label: Form,
                  name: form,
                  widget: object,
                  fields:
                    [
                      { label: Title, name: title, widget: string },
                      { label: Subtitle, name: subtitle, widget: markdown },
                    ],
                }
              - {
                  label: Quote,
                  name: quote,
                  widget: object,
                  fields:
                    [
                      { label: Text, name: text, widget: text },
                      { label: author, name: author, widget: string }
                    ],
                }
          - label: "Product"
            name: "product"
            widget: "object"
            fields:
              - { label: Base One, name: baseTwo, widget: markdown }
              - { label: Base Two, name: baseThree, widget: markdown }
              - { label: Base Three, name: baseFour, widget: markdown }
              - { label: Base Four, name: baseFive, widget: markdown }
              - { label: Quote, name: quote, widget: text }
              
